######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 15 23:01:55 2010
######################################################################

include(../plugins.pri)

QT += declarative

HEADERS += \
        videoplugin.h \
        ../mediamodel.h \
        videomodel.h

SOURCES += \
        videoplugin.cpp \
        ../mediamodel.cpp \
        videomodel.cpp
