######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 15 23:01:55 2010
######################################################################

include(../plugins.pri)

HEADERS += customcursorplugin.h customcursor.h
SOURCES += customcursorplugin.cpp customcursor.cpp

QT += declarative
