#####################################################################
# Automatically generated by qmake (2.01a) Mon Nov 15 23:01:55 2010
######################################################################

include(../plugins.pri)

HEADERS += radioplugin.h \
           radioparser.h

SOURCES += radioplugin.cpp \
           radioparser.cpp




