######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 15 23:01:55 2010
######################################################################

include(../plugins.pri)

HEADERS += pictureplugin.h \
           picturemodel.h

SOURCES += pictureplugin.cpp \
           picturemodel.cpp

