######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 15 23:01:55 2010
######################################################################

include(../plugins.pri)

QT += declarative

HEADERS += \
    animatedtilesplugin.h \
    animatedtilesitem.h \
    animatedtileshelper.h

SOURCES += \
    animatedtilesplugin.cpp \
    animatedtilesitem.cpp

RESOURCES = animatedtiles.qrc
