######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 15 23:01:55 2010
######################################################################

include(../plugins.pri)

HEADERS += qmlmodulediscoveryplugin.h qmlmodulediscovery.h
SOURCES += qmlmodulediscoveryplugin.cpp qmlmodulediscovery.cpp

QT += declarative
