######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 15 23:01:55 2010
######################################################################

include(../plugins.pri)
include($${PROJECTROOT}/src/delaysymresolution.pri)

QT += declarative

HEADERS += \
        radioplugin.h \
        ../mediamodel.h \
        ../mediainfo.h \
        radiomodel.h

SOURCES += \
        radioplugin.cpp \
        radiomodel.cpp
