######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 15 23:01:55 2010
######################################################################

include(../plugins.pri)

HEADERS += appstoreplugin.h appstore.h \
    appinstallerinterface.h \
    appinfo.h
SOURCES += appstoreplugin.cpp appstore.cpp \
    appinstallerinterface.cpp \
    appinfo.cpp

QT += declarative dbus
