######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 15 23:01:55 2010
######################################################################

include(../plugins.pri)
include(../../3rdparty/taglib/taglib.pri)
INCLUDEPATH += ../../3rdparty/taglib/ ../../3rdparty/

QT += declarative

HEADERS += musicplugin.h \
           musicmodel.h

SOURCES += musicplugin.cpp \
           musicmodel.cpp

