#!/bin/sh
for language in `cat ../../hub/supported_languages`
do find . -mindepth 1 -maxdepth 1 -type d | while read i; do OUTDIR="$i/translations" && mkdir -p $OUTDIR && lupdate $i -ts $OUTDIR/"$i"_"$language".ts; done
done
