######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 15 23:01:55 2010
######################################################################

include(../plugins.pri)

gstreamer {
    DEFINES += THUMBNAIL_GSTREAMER

    CONFIG += link_pkgconfig
    PKGCONFIG += gstreamer-0.10
}

HEADERS += \
        videoplugin.h \
        videoparser.h

SOURCES += \
        videoplugin.cpp \
        videoparser.cpp
