######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 15 23:01:55 2010
######################################################################

include(../plugins.pri)

HEADERS += \
        videoplugin.h \
        videoparser.h

SOURCES += \
        videoplugin.cpp \
        videoparser.cpp

OTHER_FILES += video.json
