#!/bin/sh
#You have discovered my treachery, Qt Components needs to be discoverable
#source with . ./qtmediahub when debugging
scriptPath=$(cd ${0%/*} && pwd -P)
HUB_RELATIVE_PATH=$scriptPath/lib:$scriptPath/resources/lib
if [ `uname` = "Darwin" ]; then
    export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:$HUB_RELATIVE_PATH
    $scriptPath/qmh.app/Contents/MacOS/qtmediahub $@
else
    export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$HUB_RELATIVE_PATH
    $scriptPath/qtmediahub $@
fi
