######################################################################
# Automatically generated by qmake (2.01a) Mon Nov 15 23:01:55 2010
######################################################################

include(../plugins.pri)

HEADERS += \
        snesplugin.h \
        snesparser.h

SOURCES += \
        snesplugin.cpp \
        snesparser.cpp

OTHER_FILES += snes.json
